##
## @file constants.py
#  @description contains constants used by the STM bootloader
#
#
##


STM_RSP_LEN_BYTE = 1

STM_CMD_HANDSHAKE = 0x7F
STM_CMD_ACK = 0x79
STM_CMD_NACK = 0x1F
STM_CMD_GET = 0x00
STM_CMD_VERSION_READ_PROTECT = 0x01
STM_CMD_GET_ID = 0x02
STM_CMD_READ_MEM = 0x11
STM_CMD_GO = 0x21
STM_CMD_WRITE_MEM = 0x31
STM_CMD_ERASE_MEM = 0x43
STM_CMD_EXT_ERASE = 0x44
STM_CMD_WRITE_PROTECT_EN = 0x63
STM_CMD_WRITE_PROTECT_DIS = 0x73
STM_CMD_READOUT_PROTECT_EN = 0x82
STM_CMD_READOUT_PROTECT_DIS = 0x92


STM_GET_RETURN_N = 0x0B

STM_RSP_GET_LEN = 12
STM_GET_ID_RSP_LEN = 2
STM_VERS_RSP_LEN = 3

STM_BOOTLOADER_MAX_BAUD = 115200
STM_BOOTLOADER_MIN_BAUD = 1200
